grid:
  rows: 9
  columns: 16
  padding: 8

widgets:
  - exe: 'Weather\weather.exe'
    row: 0
    column: 0
    rowSpan: 5
    columnSpan: 4

  - exe: 'Habits\habit_tracker.exe'
    args: [ejercicio]
    row: 5
    column: 0
    rowSpan: 4
    columnSpan: 8

  - exe: 'Habits\habit_tracker.exe'
    args: [pizza]
    row: 1
    column: 4
    rowSpan: 2
    columnSpan: 5

  - exe: 'Habits\habit_tracker.exe'
    args: [pelicula]
    row: 0
    column: 11
    rowSpan: 9 
    columnSpan: 5
